### ISSUE TITLE
The module does not compile as-is on my system.

### ISSUE THREAD

**Issue by massweet** [sebn/ansible-roles-graph#5]
The module as-is does not compile on the system I just tried to use it on. 
$ ansible-roles-graph ./roles/
Traceback (most recent call last):
  File "/usr/local/bin/ansible-roles-graph", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ansiblerolesgraph/**init**.py", line 84, in main
    graph = parse_roles(config.roles_dirs)
  File "/usr/local/lib/python2.7/dist-packages/ansiblerolesgraph/**init**.py", line 71, in parse_roles
    depended_role = dependency['role']
TypeError: string indices must be integers, not str
$
OK, so a quick edit later...

```
$ diff -U 3 __init__.py.orig __init__.py
--- __init__.py.orig    2016-06-07 13:53:10.564462723 +0100
+++ __init__.py 2016-06-07 13:54:24.641536724 +0100
@@ -68,7 +68,10 @@

             with open(path, 'r') as f:
                 for dependency in yaml.load(f.read())['dependencies']:
-                    depended_role = dependency['role']
+                    if type(dependency) is dict:
+                        depended_role = dependency['role']
+                    else:
+                        depended_role = dependency

                     builder.add_role(depended_role)
                     builder.link_roles(dependent_role, depended_role)
```

$ ansible-roles-graph ./roles/
Traceback (most recent call last):
  File "/usr/local/bin/ansible-roles-graph", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ansiblerolesgraph/**init**.py", line 87, in main
    graph = parse_roles(config.roles_dirs)
  File "/usr/local/lib/python2.7/dist-packages/ansiblerolesgraph/**init**.py", line 70, in parse_roles
    for dependency in yaml.load(f.read())['dependencies']:
TypeError: 'NoneType' object has no attribute '**getitem**'
...another quick edit...

```
$ diff -U 3 __init__.py.orig __init__.py
--- __init__.py.orig    2016-06-07 13:53:10.564462723 +0100
+++ __init__.py 2016-06-07 13:56:43.767433865 +0100
@@ -67,11 +67,18 @@
             builder.add_role(dependent_role)

             with open(path, 'r') as f:
-                for dependency in yaml.load(f.read())['dependencies']:
-                    depended_role = dependency['role']
+                try:
+                    for dependency in yaml.load(f.read())['dependencies']:
+                        if type(dependency) is dict:
+                            depended_role = dependency['role']
+                        else:
+                            depended_role = dependency
+    
+                        builder.add_role(depended_role)
+                        builder.link_roles(dependent_role, depended_role)

-                    builder.add_role(depended_role)
-                    builder.link_roles(dependent_role, depended_role)
+                except TypeError:
+                    pass

     return builder.graph

```

$ ansible-roles-graph ./roles/
$
...and there is a .png where I want as well. Thanks

**Comment by WolverineFan** [comment]
Could you edit this issue and wrap your diff output in triple-backticks? (```) I can't read your diffs but I think I just fixed one of the issues you mentioned here: #6

**Comment by massweet** [comment]
#6 does look as if it is an alternative to part of what I suggested above.
